[tools]
# languages
deno = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
go = "latest"

# npm packages
"npm:anthropic-ai/claude-code" = "latest"

[settings]
experimental = true
